# Create a GitHub action to email a report from a file at 6 a.m. daily
name: Send Email Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  send_email_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send email with report
        run: |
          echo "Report attached." | mail -s "Daily Report" -A report.txt